version: '3'

services:
 database:
  image: postgres
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DB: "application"
  ports:
    - 5432:5432

 app:
  build:
   context: .
  ports:
  - 8000:8000
  environment:
    DATABASE_URL: "postgresql://postgres:postgres@database:5432/application"
  depends_on:
  - database
