---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-hello-v0.1.0
  namespace: app-env
  labels:
    app: test-hello
    version: v0.1.0
    system: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-hello
      version: v0.1.0
      system: test-app
  template:
    metadata:
      labels:
        app: test-hello
        version: v0.1.0
        system: test-app
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      containers:
      - name: test-hello
        image: ghcr.io/cmar-apps-81/test-hello:v0.1.0
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            cpu: 40m
            memory: 64Mi
          limits:
            cpu: 150m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
                name: database
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: test-hello
  namespace: app-env
  labels:
    app: test-hello
    version: v0.1.0
    system: test-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: test-hello
    version: v0.1.0
    system: test-app

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hello
  namespace: app-env
spec:
  maxReplicas: 50
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-hello-v0.1.0
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

