name: Pull request

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17
    steps:
      - uses: actions/checkout@v3
      - name: Executing tests
        uses: ./.github/actions/python/tests
